✨ feat: 공통 예외 처리 기능 추가
Team-Talking-Potatoes/WeGo_BE pull request #12
Opened 2024-11-26 03:47 UTC by tjvm0877

## PR 타입

- [x] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Performance Improvement
- [ ] Bugfix
- [ ] Test Code
- [ ] Code style update (formatting, local variables)
- [ ] Other... Please describe:

## 개요

- 이슈에서 말씀드렸듯 서비스의 일관되고 세부적인 예외 처리를 위해서 공통 예외 처리기능을 추가하였습니다.

## 작업 및 변경 사항

1. **`GlobalExceptionHandler`를 추가**  
    - `@ControllerAdvice` 어노테이션으로 모든 예외를 한 곳에서 처리할 수 있습니다.
    - 추가로 스프링 및 라이브러리 등 자체적으로 발생하는 예외는 `@ExceptionHandler` 으로 추가해서 적절한 Error Response를 만들고 비지니스 요구사항에 예외일 경우 `CustomException` 으로 통일성 있게 처리하는 것을 목표로 하였습니다.
2. **ErrorResponse객체를 추가**
    - Error Response를 통해 서비스가 항상 동일한 형태의 Error Response를 가질 수 있도록 하였습니다. 이를 통해  클라이언트에서 예외 처리를 항상 동일한 로직으로 처리 할 수 있는 것을 의도하였습니다.
3. **enum 타입 추가**
    - 메시지의 중복을 방지하기 위해서 에러 코드들을 enum 타입으로 한 곳에서 관리하도록 하였습니다..
4. **`CustomException` 추가**
    -  개발자가 직접 발생시키는 Exception의 최상위 Exception을 추가하였습니다.
    - 최상위 `CustomException`을 기준으로 예외를 발생시키면 통일감 있는 예외 처리를 가질 수 있습니다. 비니지스 로직을 수행하는 코드 흐름에서 로직의 흐름을 진행할 수 없는 상태인 경우에는 적절한 CustomException 중에 하나를 예외를 발생 시키거나 직접 정의하게 됩니다.
    - 이렇게 발생하는 모든 예외는 `GlobalExceptionHandler`의 `handleCustomException()` 에서 동일하게 핸들링 됩니다. 그 결과 예외 발생시 알람을 받는 등의 추가적인 행위도 손쉽게 가능합니다. 또한 `CustomException` 클래스의 하위 클래스 중에서 특정 예외에 대해서 다른 알람을 받는 등의 더 디테일한 핸들링도 가능해질것이라 생각합니다.

close #11

2024-11-26 09:33 UTC, jickDo requested changes
ErrorResponse 쪽을 내부 클래스로 선언하시면서 레이어 형식으로 나타내셨네요 이런 방식으로도 풀어낼수 있다는것을 배웠습니다.

2024-11-26 09:33 UTC, jickDo commented on src/main/java/potatoes/server/error/ErrorCode.java
> +	INVALID_TYPE_VALUE(400, "INVALID_TYPE_VALUE", " Invalid Type Value");
P1: " Invalid Input Value", " Invalid Type Value" 앞에 공백이 들어가 있네요

2024-11-26 09:33 UTC, jickDo commented on src/main/java/potatoes/server/error/ErrorCode.java
> +	INVALID_TYPE_VALUE(400, "INVALID_TYPE_VALUE", " Invalid Type Value");
P5: 요건 진짜 사소한 의견인데 납득가능한 일관성이 있는 정렬이 되어있으면 좋겠다는 생각 이있습니다. 
Ex) http status 번호가 낮은 순으로 먼저 나열

2024-11-26 09:33 UTC, jickDo commented on src/main/java/potatoes/server/error/ErrorCode.java
> +	INVALID_TYPE_VALUE(400, "INVALID_TYPE_VALUE", " Invalid Type Value");
P3: **400,500**은 저희가 흔히 사용하는 값이긴 해도 **매직넘버** 이니까, 따로 상수로 선언하거나 더좋은 방법은 **HttpStatus.BAD_REQUEST.value()** 처럼 이미 존재하는 상수값을 불러와서 명확한 이름을 제시하는 쪽이 더좋아 보입니다.

2024-11-26 09:33 UTC, jickDo commented on src/main/java/potatoes/server/error/ErrorResponse.java
> +		this.code = code.getCode();
P3: 사소한 것이긴한데 위의 ErrorResponse는 message, parameter, code 순인데 아래sms message, code, parameter 순입니다. 혹시 특별한 이유가 있을까욥??

2024-11-26 09:33 UTC, jickDo commented on src/main/java/potatoes/server/error/ErrorResponse.java
> +	private List<FieldError> parameter;
P5: 변수명이 parameter가 된것이 어떤 의미인지 궁금해요!
변수명은 명확한 이름을 가지는게 맞다는 입장이라 fieldErrors나 fieldErrorList 같은 이름이면 더욱 명확하다는 생각이 듭니다.

2024-11-26 09:33 UTC, jickDo commented on src/main/java/potatoes/server/error/ErrorResponse.java
> +	}
P2: 정적팩토리 메소드의 장점중 하나는 명확한 이름을 가질 수 있다는 장점이 있다고 생각해요.
 물론 of를 오버로드 함으로써 얻는 장점으로 코드 간결성이 있겠지만, 아래 사진처럼 대표적인 단점으로 내부 구조를 명확히 알고 있어야 한다는 부분이 있습니다.
현재는 of라는 네이밍을 가진 함수가 복수개 나오고 있는데 사용하는 입장에서는 혼란스러울 것 같다는 생각이 들어요 그래서 조금 명확한 이름을 주는것이 좋겠다라는 생각이 들었습니다...!

대표적인 정정팩토리의 네이밍 컨벤션에 인자가 한개일때 from을 쓰고 복수개일때 of를 쓴다처럼 기본 컨벤션을 따라가는 것도 좋고, 좀더 커스텀적인 이름을 가져가도 좋을것 같습니다.

<img width="1056" alt="image" src="https://github.com/user-attachments/assets/a70e2a6b-e77a-4899-ada3-0efe62ed05e7">


> 이부분은 아래 개선점과 충돌하는 부분이 있어서 아래 읽어보고 오시면 좋습니다...!

2024-11-26 09:33 UTC, jickDo commented on src/main/java/potatoes/server/error/GlobalExceptionHandler.java
> +		return ResponseEntity.status(400).body(response);
P3: 요것도 HttpStatus 같은 곳에서 가져와서 명확한 의도를 표시하는게 좋아보입니다. 
물론 400이 모두가 아는 숫자지만 406같은 에러가 나왔을때 표시 해주기 시작하면 일관성이 무너져서 그냥 400이 다른의미를 가졌는지 생각해볼것 같습니다.

2024-11-26 09:33 UTC, jickDo commented on src/main/java/potatoes/server/error/GlobalExceptionHandler.java
> +		return ResponseEntity.status(errorCode.getStatus()).body(response);
P3: 4개의 코드의 비슷한 로직이 나오는거 같습니다. 
3가지 패턴의로 ErrorResponse.of를 사용하는 것같은데 이 부분을 오버로드 된 메서드들로 생성하고 return 에 그 함수를 가져다 쓰면 조금 깔끔하고 역활분리가 될것같다는 생각이 들어요.

````java
 private static final ResponseEntity<ErrorResponse> handleError(ErrorCode errorCode) {
        return ResponseEntity
            .status(errorCode.getStatus())
            .body(ErrorResponse.of(errorCode));
    }
````

    이런 느낌이 되겠죠?
    
    이러면 `return handleError(ErrorCode.INTERNAL_SERVER_ERROR); `이 되면서 명확한 느낌이 될것 같습니다.
    
    물론, 이렇게 진행하면 이전의 of가 중복 되던곳의 메서드 네이밍을 그대로 사용해야 하겠네요

2024-11-27 06:22 UTC, tjvm0877 commented on src/main/java/potatoes/server/error/ErrorCode.java
> +	INVALID_TYPE_VALUE(400, "INVALID_TYPE_VALUE", " Invalid Type Value");
오타네요. 수정하겠습니다.

2024-11-27 06:38 UTC, tjvm0877 commented on src/main/java/potatoes/server/error/ErrorCode.java
> +	INVALID_TYPE_VALUE(400, "INVALID_TYPE_VALUE", " Invalid Type Value");
**"P5: 요건 진짜 사소한 의견인데 납득가능한 일관성이 있는 정렬이 되어있으면 좋겠다는 생각 이있습니다."**
Ex) http status 번호가 낮은 순으로 먼저 나열
-> 음...번호가 낮은 순서로 하는 건 아닌 것 같고. 아래 예시와 같이 예외가 발생하는 위치 혹은 도메인 끼리 묶여있는 것으로 충분할 것 같습니다.  
```java
    // Common
    INVALID_INPUT_VALUE(400, "INVALID_INPUT_VALUE", " Invalid Input Value"),
    METHOD_NOT_ALLOWED(405, "METHOD_NOT_ALLOWED", " Invalid Input Value"),
    ENTITY_NOT_FOUND(400, "ENTITY_NOT_FOUND", " Entity Not Found"),
    INTERNAL_SERVER_ERROR(500, "INTERNAL_SERVER_ERROR", "Server Error"),
    INVALID_TYPE_VALUE(400, "INVALID_TYPE_VALUE", " Invalid Type Value"),
    HANDLE_ACCESS_DENIED(403, "HANDLE_ACCESS_DENIED", "Access is Denied"),

    // Member
    EMAIL_DUPLICATION(400, "EMAIL_DUPLICATION", "Email is Duplication"),
    LOGIN_INPUT_INVALID(400, "LOGIN_INPUT_INVALID", "Login input is invalid"),

    // Gethering
    GATHERING_NOT_FOUND(400, "GATHERING_NOT_FOUND", "Gathering not found");
```
추후 저희들이 선언하는 예외들을 이런식으로 묶으면 보기 편하지 않을까? 라는 생각으로 작성했습니다.


**"P3: 400,500은 저희가 흔히 사용하는 값이긴 해도 매직넘버 이니까, 따로 상수로 선언하거나 더좋은 방법은 HttpStatus.BAD_REQUEST.value() 처럼 이미 존재하는 상수값을 불러와서 명확한 이름을 제시하는 쪽이 더좋아 보입니다."**

현재 코드에서는 이미 다음과 같은 방식으로 이 문제를 해결하고 있습니다:
1. ErrorCode enum을 사용하여 상태 코드를 관리하고 있습니다. 이는 매직 넘버를 피하고 의미 있는 이름을 부여하는 좋은 방법입니다.
2. @ControllerAdvice를 통해 전역적으로 예외를 처리하고 있으며, 각 예외 처리 메서드에서 ErrorCode를 사용하여 상태 코드를 설정하고 있습니다.
3. ResponseEntity.status(errorCode.getStatus())와 같이 ErrorCode에서 정의한 상태 코드를 사용하고 있어, 이미 명확하고 일관된 방식으로 HTTP 상태 코드를 관리하고 있습니다.  

따라서 현재 구현은 이미 매직 넘버를 피하고 명확한 상수를 사용하는 방식을 채택하고 있습니다. HttpStatus enum을 직접 사용하는 것도 좋은 방법이지만, 현재 ErrorCode enum을 통해 프로젝트에 특화된 에러 코드와 메시지를 함께 관리할 수 있어 더 유연하고 확장 가능한 방식이라고 생각합니다.

다만, `GlobalExceptionHandler `에서 `MethodArgumentTypeMismatchException` 처리 부분에서는 직접 400을 하드코딩하고 있으므로, 이 부분을 ErrorCode.INVALID_TYPE_VALUE.getStatus()로 변경하면 더 좋을 것 같네요.

2024-11-27 06:41 UTC, tjvm0877 commented on src/main/java/potatoes/server/error/ErrorResponse.java
> +		this.code = code.getCode();
딱히 이유는 없었습니다. 코드를 짜고 수정하는 과정에서 미처 생각하지 못한 부분이네요. 아래 순서로 고정하고자 합니다.
```java
private ErrorResponse(ErrorCode code, List<FieldError> errors) {
  this.code = code.getCode();
  this.message = code.getMessage();
  this.parameter = errors;
}
```

2024-11-27 06:47 UTC, tjvm0877 commented on src/main/java/potatoes/server/error/ErrorResponse.java
> +	private List<FieldError> parameter;
동의합니다. 다만, 저희에게 제공된 왠만하면 명세서를 그대로 따라가고자 했습니다. 원래 VALIDATION_ERROR는 다음과 같았고 
```json
{
  "code": "VALIDATION_ERROR",
  "parameter": "email",
  "message": "유효한 이메일 주소를 입력하세요"
}
```
제가 짠 코드의 응답은 다음과 같습니다.
```json
{
  "code": "VALIDATION_ERROR",
  "message": "Invalid Input Value",
  "parameter": [
    {
      "field": "email",
      "value": "",
      "message": "유효한 이메일 주소를 입력하세요"
    }
  ]
}
```

만약 바꾼다면 `validation`같은 이름으로 하면 좋을 것 같네요.

2024-11-27 06:49 UTC, hyunmuam commented on src/main/java/potatoes/server/error/GlobalExceptionHandler.java
> +		return ResponseEntity.status(400).body(response);
ResponseEntity Builder메서드에서 이미 `this(HttpStatusCode.valueOf(statusCode));`로 처리를 하고 있기 때문에 `ErrorCode`관리 만 잘해도 상관없는 문제라고 생각했습니다.

+이부분은 `Errorcode`에 선언(게다가 이미 선언해놨네요..😂)하고 그 값을 가져오는것이 맞는 것 같습니다.

2024-11-27 06:54 UTC, tjvm0877 commented on src/main/java/potatoes/server/error/ErrorResponse.java
> +	}
말씀하신 대표적인 정적팩토리 메소드를 찾아봤습니다.
사용한 의도는 다형성에 조금더 초점을 맞추긴했지만 매개변수의 갯수에 따라 `from`과 `of`로 구분을 명확하게 하면 더 좋은 것 같습니다.

2024-11-27 07:00 UTC, tjvm0877 commented on src/main/java/potatoes/server/error/GlobalExceptionHandler.java
> +		return ResponseEntity.status(errorCode.getStatus()).body(response);
인라인으로 하자는 말씀이신거죠?
코드를 작성할 시점에 이렇게 분리해 놓은 이유는 추가적인 기능(예를들어 error logging, 알람)을 염두해두긴 했습니다.
그 경우 response에 대한 추가적인 처리가 있지 않을까라고 생각을 했고 따로 분리하긴 했지만. 지금은 고려할 필요가 없기 때문에 인라인으로하고 나중에 변경해도 될 것 같네요.

패턴이 똑같아도 특정 예외에 대해서 다른 알람을 받는 등의 더 디테일한 핸들링을 위해서 분리했습니다.

2024-11-27 07:09 UTC, tjvm0877 commented on src/main/java/potatoes/server/error/GlobalExceptionHandler.java
> +		return ResponseEntity.status(errorCode.getStatus()).body(response);
음... 메서드 네이밍을 적용하기로 생각했는데 이러면 약간 머리가 아프네요. 관련해서 한번 생각해보겠습니다.

2024-11-27 07:29 UTC, tjvm0877 commented on src/main/java/potatoes/server/error/GlobalExceptionHandler.java
> +		return ResponseEntity.status(errorCode.getStatus()).body(response);
+ 제가 코드를 짜면서 중요하게 생각한 부분이 특정 예외에 대해서 다른 알람을 받는 등의 더 디테일한 핸들링을 생각하면서 짰기 때문에 공통화하여 따로 메서드 추출을 하진 않았습니다. 어떤 핸들링이 추가될지 아직 모르니까요.

2024-11-27 09:21 UTC, jickDo commented on src/main/java/potatoes/server/error/ErrorCode.java
> +	INVALID_TYPE_VALUE(400, "INVALID_TYPE_VALUE", " Invalid Type Value");
오오... 에러를 도메인으로 나누는 생각은 안해봤는데 예시로 보니까 괜찮은 방법인것 같네요!!
위방식대로 가면서 필요한 것 추가하면서 나아가다보면 얼추 개선방향이 보일듯 합니다.

그리고 지금 당장 보았을때 걱정되는 부분이 있다면 위 방식에서는 **common은 조심**해야 할것 같아요. 

이전에 멀티모듈 고도화 진행중에 네이버쪽 멀티모듈 고도화 영상에 나온 내용을 빌려 설명하자면, common이라는 모듈의 존재는 모든것을 수용할 수 있다보니 뒤로 갈수록 규모가 비대해지는 문제가 있었다고 합니다. 

이를 어플리케이션단으로 생각해보아도 특정 도메인 예외가 다른곳에서 사용되는 경우가 흔하다고 생각합니다. 즉 애매해진 예외는 common으로 모일것이고 나중에는 비대해진 common이 생길것이라고 생각해요

**결국 비대해진 common의 존재는 예외를 묶는 의미를 희미하게 만들 우려가 있다고 생각해요**

결론적으로, 도메인 영역의 예외 방식으로 가고 common은 조금 조심히 사용하는 쪽으로 가는것 어떨까요!

2024-11-27 09:46 UTC, jickDo commented on src/main/java/potatoes/server/error/ErrorResponse.java
> +	private List<FieldError> parameter;
아 기존 명세서 변수명이 파라미터 였군요... 이건 생각못해본 이유네요 😅
평소 코드에 대해 고민 많이 하시는 것같아 특별한 이유가 있을것같고 무슨 이유일까 해서 여쭤봤습니당

2024-11-27 09:54 UTC, jickDo commented on src/main/java/potatoes/server/error/GlobalExceptionHandler.java
> +		return ResponseEntity.status(errorCode.getStatus()).body(response);
현재 패턴에서 수평적 확장으로 메서드들이 생길것 같아서 메서드 추출을 말했었는데, 추가 사항에 대해 고려중인거군요.  그럼 지금 추출하는거 보다 형태가 잡히고 리팩토링하는 방향이 좋다고 생각합니다!

2024-11-27 09:56 UTC, jickDo approved these changes
공통 예외 기능 구현하시는라 고생하셨습니다...!
코드에서 많은 고민의 흔적이 보여서 의견을 공유하는 것으로도 많은 것을 배울 수 있었습니다. 감사합니다 :)

2024-11-27 12:24 UTC, tjvm0877 commented on src/main/java/potatoes/server/error/ErrorCode.java
> +	INVALID_TYPE_VALUE(400, "INVALID_TYPE_VALUE", " Invalid Type Value");
@jickDo 동의합니다. 다만 이부분도 규모가 커지면 리펙토링하는 방향으로 잡는게 좋을 것 같습니다.

2024-11-27 12:25 UTC, merged