feature: 모임 API 구현
Team-Talking-Potatoes/WeGo_BE pull request #17
Opened 2024-11-28 14:01 UTC by jickDo

## PR 타입

- [X] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Performance Improvement
- [ ] Bugfix
- [ ] Test Code
- [ ] Code style update (formatting, local variables)
- [ ] Other... Please describe:

## 개요

 모임 목록 조회
 모임 생성
 모임 상세 조회
 특정 모임의 참가자 목록 조회
 모임 취소
 모임 참여
 모임 참여 취소

## 작업 및 변경 사항

기존 모임 관련 API 중 로그인된 사용자가 참석한 모임 목록 조회를 제외한 API 구현

### 공유 하고 싶은 내용 및 참고 자료

- 스웨거 문서상으로 기존 형식과 최대한 비슷하게 하려고 컨트롤러 영역의 어노테이션이 많이 붙어있는 경향이 있습니다. 이부분은 추후 이야기 통해서 조정하기 위해 극단적으로 붙일 수 있는 기능을 다 붙인 형태입니다.

- 페이지네이션 인터페이스를 생성하고 내부에서 기초값 세팅을(limit, offset, sortOrder, sort ...) 진행하고 싶었는데 스웨거상 작업(디폴트값 20표시)같은 것을 표시하는라 일관성이 없이 파라미터와 인터페이스 양측에서 기초값세팅이나 밸리데이션이 되어있습니다. 저는 밸리데이션은 api파라미터에서 진행하고, 기초값세팅은 dto 내부에서 하여 역할을 분리하고 싶은데 이부분 이야기 해보고 싶습니다.

- 테스트는 서비스 영역만 되어있습니다.

close #7

2024-11-29 09:42 UTC, tjvm0877 requested changes
정말 수고하셨습니다. 제가 확인한 코드 부분들 확인하시고 답변해주세요.

공유 하고 싶은 내용에 대한 제 생각도 함께 공유해 드립니다.
1. "스웨거 문서상으로 기존 형식과 최대한 비슷하게 하려고 컨트롤러 영역의 어노테이션이 많이 붙어있는 경향이 있습니다. 이부분은 추후 이야기 통해서 조정하기 위해 극단적으로 붙일 수 있는 기능을 다 붙인 형태입니다."
-> 스웨거를 사용하기로 결정한 이상 클라이언트측에게 최대한 많은 정보를 보여주는 것이 좋다고 생각합니다. 그렇기 때문에 딱히 이질감은 없었습니다. ㅎ
2. "페이지네이션 인터페이스를 생성하고 내부에서 기초값 세팅을(limit, offset, sortOrder, sort ...) 진행하고 싶었는데 스웨거상 작업(디폴트값 20표시)같은 것을 표시하는라 일관성이 없이 파라미터와 인터페이스 양측에서 기초값세팅이나 밸리데이션이 되어있습니다. 저는 밸리데이션은 api파라미터에서 진행하고, 기초값세팅은 dto 내부에서 하여 역할을 분리하고 싶은데 이부분 이야기 해보고 싶습니다."
-> 죄송합니다. 잘 이해를 못했습니다. "밸리데이션은 api파라미터에서 진행"이라는게 `@RequestBody`를 말씀하시는 건가요? 아니면 쿼리파라미터?
3. "테스트는 서비스 영역만 되어있습니다."
-> 만약 테스트를 부분적으로 한다면 E2E테스트가 더 적합하지 않았나 하는 아쉬움이 있었습니다. 단위 테스트가 중요하지 않은 건 아니지만 통합테스트의 중요성이 더 중요하다고 생각하기 때문입니다.
4. "현재 api는 서로의 스타일을 확인하기 위함이라는 생각이며, 기획 변경에 따라 api도 엎어질것 같아 커스텀 예외는 지금 생성하지 않고 아무 예외를 던지는 방식으로 진행했습니다. 이 부분은 필요하다고 생각하시면 커스텀 예외로 전환해서 던지게 작업 진행하겠습니다."
-> 음...엄격하게 커스탐 예외로 던져야됩니다! 는 아니지만 디테일하게 계획되지 않아 약간의 변동가능성이 있다고 해도 같은 기능에 대해서는 동일한 흐름을 타야 된다고 생각합니다. 아시다 싶이 커스텀 예외냐, 스프링 혹은 라이브러리에서 발생한 예외냐에 따라서 타는 흐름이 달라지기 때문에 차라리 `GatheringException`같은 걸 새로 만드시고 사용하셔서 변경은 되겠지만 동일한 처리 흐름을 만들어주 셨으면 더 좋지 않았나 싶습니다.

2024-11-29 09:42 UTC, tjvm0877 commented on src/main/java/potatoes/server/dto/CreateGatheringResponse.java
> +@Builder
P3: 응답용 record에 빌더를 적용하느냐는 생각해봐야 될 문제 같습니다. 빌더가 실질적으로 사용되는 부분은 record내부에서만 사용되기 때문에 사용성에 대해서 의구심이 생기네요.
+다른 record들의 사용방식도 마찬가지로 한번 생각해 볼만한 것 같습니다.

2024-11-29 09:42 UTC, tjvm0877 commented on src/main/java/potatoes/server/service/GatheringService.java
> +		return gathering;
P1: 이부분은 repository에 메서드를 만들 때 응답값을 Optional로 바꾸면 더 좋지 않을까 싶습니다. 


```java
// GatheringRepository.java
public interface GatheringRepository extends JpaRepository<Gathering, Long> {
    ...
    Optional<Gathering> findByIdAndCanceledAtIsNull(Long id)
}
```
이렇게 선언할 경우 
```java
// GatheringService.java
...
private Gathering findNotCanceledGathering(Long gatheringId) {
    Gathering gathering = gatheringRepository.findByIdAndCanceledAtIsNull(gatheringId).orElseThrow(
        () -> new NotFoundException("존재하지 않는 모임이거나 이미 취소된 모임입니다.")
    );
    return gathering;
}
```
이렇게 표현되는게 if문으로 null체크하는 것 보다 더 깔끔해보입니다.

2024-11-29 13:10 UTC, jickDo commented
> 정말 수고하셨습니다. 제가 확인한 코드 부분들 확인하시고 답변해주세요.
> 
> 공유 하고 싶은 내용에 대한 제 생각도 함께 공유해 드립니다.
> 
> 1. "스웨거 문서상으로 기존 형식과 최대한 비슷하게 하려고 컨트롤러 영역의 어노테이션이 많이 붙어있는 경향이 있습니다. 이부분은 추후 이야기 통해서 조정하기 위해 극단적으로 붙일 수 있는 기능을 다 붙인 형태입니다."
>    -> 스웨거를 사용하기로 결정한 이상 클라이언트측에게 최대한 많은 정보를 보여주는 것이 좋다고 생각합니다. 그렇기 때문에 딱히 이질감은 없었습니다. ㅎ
> 2. "페이지네이션 인터페이스를 생성하고 내부에서 기초값 세팅을(limit, offset, sortOrder, sort ...) 진행하고 싶었는데 스웨거상 작업(디폴트값 20표시)같은 것을 표시하는라 일관성이 없이 파라미터와 인터페이스 양측에서 기초값세팅이나 밸리데이션이 되어있습니다. 저는 밸리데이션은 api파라미터에서 진행하고, 기초값세팅은 dto 내부에서 하여 역할을 분리하고 싶은데 이부분 이야기 해보고 싶습니다."
>    -> 죄송합니다. 잘 이해를 못했습니다. "밸리데이션은 api파라미터에서 진행"이라는게 `@RequestBody`를 말씀하시는 건가요? 아니면 쿼리파라미터?
> 3. "테스트는 서비스 영역만 되어있습니다."
>    -> 만약 테스트를 부분적으로 한다면 E2E테스트가 더 적합하지 않았나 하는 아쉬움이 있었습니다. 단위 테스트가 중요하지 않은 건 아니지만 통합테스트의 중요성이 더 중요하다고 생각하기 때문입니다.
> 4. "현재 api는 서로의 스타일을 확인하기 위함이라는 생각이며, 기획 변경에 따라 api도 엎어질것 같아 커스텀 예외는 지금 생성하지 않고 아무 예외를 던지는 방식으로 진행했습니다. 이 부분은 필요하다고 생각하시면 커스텀 예외로 전환해서 던지게 작업 진행하겠습니다."
>    -> 음...엄격하게 커스탐 예외로 던져야됩니다! 는 아니지만 디테일하게 계획되지 않아 약간의 변동가능성이 있다고 해도 같은 기능에 대해서는 동일한 흐름을 타야 된다고 생각합니다. 커스텀 예외냐, 스프링 혹은 라이브러리에서 발생한 예외냐에 따라서 타는 흐름이 달라지기 때문에 차라리 `GatheringException`같은 걸 새로 만드시고 사용하셔서 변경은 되겠지만 동일한 처리 흐름을 만들어주 셨으면 더 좋지 않았나 싶습니다.

### 1번 의견에 대해서는 적극 동의합니다. 스웨거상으로 필요한 정보에 대한 방향을 표현을 하는 방향으로 진행하겠습니다.

---

### 2번은 쿼리 파라미터에 대한 의견이였는데 페이지네이션에 (limit, offset, sortOrder, sort ...)정보들은 항상 등장하는것 같아 **Paginator** 라는 인터페이스를 생성하고

```java
public interface Paginator {
	int getOffset();

	int getLimit();

	String getSortBy();

	String getSortOrder();
}

```

 **PageableFactory**에서  페이지네이션 객체(Pageable, Sort)을 생성하는 기능을 따로 빼뒀습니다.
 
```
 @Component
public class PageableFactory {
	public Pageable create(Paginator request) {
		return PageRequest.of(calculatePageNumber(request), request.getLimit(), createSort(request));
	}

	........ 내용 생략
}
```

  페이지네이션에서 사용하는 dto에 한해서 **Paginator** 상속받으면 **PageableFactory**에 파라미터로 전달가능하니 DTO 내부에서 아래처럼 디폴트를 각 dto에 맞게 만들어 줄 수 있습니다.

```java
	@Override
	public String getSortOrder() {
		return sortOrder != null ? sortOrder : "asc";
	}
```
### 여기까지는 현재 구현에 대한 설명이였고, 이러한 방식을 사용했을 때 얻을 수 있는 장점은 컨트롤러단에서 해야하는 두가지 기능중 2번을 숨길 수 있다는 장점이 있습니다.

1. 데이터의 정합성? 체크 (밸리데이션)
2. 디폴트값 설정

컨트롤러 단에서 두가지 모두 가능하지만 컨트롤러 역할이 커지는 것이 걱정되었고, 역할을 분리 한다고 했을 떄 기본값 설정이 데이터 전달 객체인 dto가 하는게 좋겠다는 의견이었습니다.

`@RequestParam(required = false, defaultValue = "0")`

이러한 코드가

`@RequestParam(required = false)` 와 

```java
	@Override
	public String getLimit() {
		return sortLimit != null ? sortOrder : 0;
	}
```

로 분리될것입니다.

---

### 3번의 경우는 반박의 여지가 없습니다 ㅎㅎ, **다만 중요도 목적에서 단위테스트 더 중요해!** 요런느낌보다는 E2E 테스트를 작성해본 경험이 없던지라 정해진 기간내에 할 수 있는 최선의 테스트인 단위 테스트를 먼저 작성했습니다. 이 부분은 저의 부족함을 인정하며 주말 안까지 작성해서 pr에 추가해보겠습니다...!

---

### 4번은 중요도로 일을 나눴을 때, **예외는 살짝 갈아끼우는 느낌 아닌가...?** 싶어서 중요도를 낮게 책정하여 배제했던 경향이 있습니다. 현재 작성되어있는 공통 예외 방식에 대한 적응도 해야하니 3번의 기능을 진행하며 같이 변경하겠습니다

2024-11-29 13:30 UTC, jickDo commented on src/main/java/potatoes/server/service/GatheringService.java
> +		return gathering;
놓치고 있던 부분 말씀해주셔서 감사합니다 :)

추가적으로 **findNotCanceledGathering** 는 이름이 명확하고, 여러곳에서 사용 되지만 내부 구조를 몰라도 되는 전형적인 **요청 메시지를 던지는** 형태로 보여져서 바로 리턴하게 인라인화 해두었습니다.

```java
private Gathering findNotCanceledGathering(Long gatheringId) {
	return gatheringRepository.findByIdAndCanceledAtIsNull(gatheringId).orElseThrow(
		() -> new NotFoundException("존재하지 않는 모임이거나 이미 취소된 모입입니다.")
	);
}
```

2024-11-29 14:13 UTC, jickDo commented on src/main/java/potatoes/server/dto/CreateGatheringResponse.java
> +@Builder
레코드 타입에 관성적으로 빌더를 달고있어서 생각해본적 없는데 현재 반환형에 대해서는 빌더를 제거 하는 방향이 맞겠네요
다른 레코드들의 사용방식에 대해서는 의견이 있다면 듣고싶습니다..!

2024-11-29 14:15 UTC, tjvm0877 commented
> > 정말 수고하셨습니다. 제가 확인한 코드 부분들 확인하시고 답변해주세요.
> > 공유 하고 싶은 내용에 대한 제 생각도 함께 공유해 드립니다.
> > 
> > 1. "스웨거 문서상으로 기존 형식과 최대한 비슷하게 하려고 컨트롤러 영역의 어노테이션이 많이 붙어있는 경향이 있습니다. 이부분은 추후 이야기 통해서 조정하기 위해 극단적으로 붙일 수 있는 기능을 다 붙인 형태입니다."
> >    -> 스웨거를 사용하기로 결정한 이상 클라이언트측에게 최대한 많은 정보를 보여주는 것이 좋다고 생각합니다. 그렇기 때문에 딱히 이질감은 없었습니다. ㅎ
> > 2. "페이지네이션 인터페이스를 생성하고 내부에서 기초값 세팅을(limit, offset, sortOrder, sort ...) 진행하고 싶었는데 스웨거상 작업(디폴트값 20표시)같은 것을 표시하는라 일관성이 없이 파라미터와 인터페이스 양측에서 기초값세팅이나 밸리데이션이 되어있습니다. 저는 밸리데이션은 api파라미터에서 진행하고, 기초값세팅은 dto 내부에서 하여 역할을 분리하고 싶은데 이부분 이야기 해보고 싶습니다."
> >    -> 죄송합니다. 잘 이해를 못했습니다. "밸리데이션은 api파라미터에서 진행"이라는게 `@RequestBody`를 말씀하시는 건가요? 아니면 쿼리파라미터?
> > 3. "테스트는 서비스 영역만 되어있습니다."
> >    -> 만약 테스트를 부분적으로 한다면 E2E테스트가 더 적합하지 않았나 하는 아쉬움이 있었습니다. 단위 테스트가 중요하지 않은 건 아니지만 통합테스트의 중요성이 더 중요하다고 생각하기 때문입니다.
> > 4. "현재 api는 서로의 스타일을 확인하기 위함이라는 생각이며, 기획 변경에 따라 api도 엎어질것 같아 커스텀 예외는 지금 생성하지 않고 아무 예외를 던지는 방식으로 진행했습니다. 이 부분은 필요하다고 생각하시면 커스텀 예외로 전환해서 던지게 작업 진행하겠습니다."
> >    -> 음...엄격하게 커스탐 예외로 던져야됩니다! 는 아니지만 디테일하게 계획되지 않아 약간의 변동가능성이 있다고 해도 같은 기능에 대해서는 동일한 흐름을 타야 된다고 생각합니다. 커스텀 예외냐, 스프링 혹은 라이브러리에서 발생한 예외냐에 따라서 타는 흐름이 달라지기 때문에 차라리 `GatheringException`같은 걸 새로 만드시고 사용하셔서 변경은 되겠지만 동일한 처리 흐름을 만들어주 셨으면 더 좋지 않았나 싶습니다.
> 
> ### 1번 의견에 대해서는 적극 동의합니다. 스웨거상으로 필요한 정보에 대한 방향을 표현을 하는 방향으로 진행하겠습니다.
> ### 2번은 쿼리 파라미터에 대한 의견이였는데 페이지네이션에 (limit, offset, sortOrder, sort ...)정보들은 항상 등장하는것 같아 **Paginator** 라는 인터페이스를 생성하고
> ```java
> public interface Paginator {
> 	int getOffset();
> 
> 	int getLimit();
> 
> 	String getSortBy();
> 
> 	String getSortOrder();
> }
> ```
> 
> **PageableFactory**에서 페이지네이션 객체(Pageable, Sort)을 생성하는 기능을 따로 빼뒀습니다.
> 
> ```
>  @Component
> public class PageableFactory {
> 	public Pageable create(Paginator request) {
> 		return PageRequest.of(calculatePageNumber(request), request.getLimit(), createSort(request));
> 	}
> 
> 	........ 내용 생략
> }
> ```
> 
> 페이지네이션에서 사용하는 dto에 한해서 **Paginator** 상속받으면 **PageableFactory**에 파라미터로 전달가능하니 DTO 내부에서 아래처럼 디폴트를 각 dto에 맞게 만들어 줄 수 있습니다.
> 
> ```java
> 	@Override
> 	public String getSortOrder() {
> 		return sortOrder != null ? sortOrder : "asc";
> 	}
> ```
> 
> ### 여기까지는 현재 구현에 대한 설명이였고, 이러한 방식을 사용했을 때 얻을 수 있는 장점은 컨트롤러단에서 해야하는 두가지 기능중 2번을 숨길 수 있다는 장점이 있습니다.
> 1. 데이터의 정합성? 체크 (밸리데이션)
> 2. 디폴트값 설정
> 
> 컨트롤러 단에서 두가지 모두 가능하지만 컨트롤러 역할이 커지는 것이 걱정되었고, 역할을 분리 한다고 했을 떄 기본값 설정이 데이터 전달 객체인 dto가 하는게 좋겠다는 의견이었습니다.
> 
> `@RequestParam(required = false, defaultValue = "0")`
> 
> 이러한 코드가
> 
> `@RequestParam(required = false)` 와
> 
> ```java
> 	@Override
> 	public String getLimit() {
> 		return sortLimit != null ? sortOrder : 0;
> 	}
> ```
> 
> 로 분리될것입니다.
> 
> ### 3번의 경우는 반박의 여지가 없습니다 ㅎㅎ, **다만 중요도 목적에서 단위테스트 더 중요해!** 요런느낌보다는 E2E 테스트를 작성해본 경험이 없던지라 정해진 기간내에 할 수 있는 최선의 테스트인 단위 테스트를 먼저 작성했습니다. 이 부분은 저의 부족함을 인정하며 주말 안까지 작성해서 pr에 추가해보겠습니다...!
> ### 4번은 중요도로 일을 나눴을 때, **예외는 살짝 갈아끼우는 느낌 아닌가...?** 싶어서 중요도를 낮게 책정하여 배제했던 경향이 있습니다. 현재 작성되어있는 공통 예외 방식에 대한 적응도 해야하니 3번의 기능을 진행하며 같이 변경하겠습니다

2번의견도 괜찮아 보입니다. 저희가 페이지네이션을 많이 사용하게 될 것 같은데 이부분은 직찬님이 더 잘아시는 것 같으니 적용해보고 저희끼리 문제가 있다고 판단되면 그때 리펙토링해봐도 될 것 같아요 ^^

2024-12-01 13:37 UTC, tjvm0877 reviewed
수고하셨습니다. 구현하신 페이징 방법 방식을 참고해서 리뷰도 만들어야겠습니다.

2024-12-01 13:37 UTC, tjvm0877 commented on src/test/java/potatoes/server/ServerApplicationTests.java
> +@EnableJpaAuditing
P3: 이건 붙이신 이유가 있나요?

2024-12-01 13:41 UTC, jickDo commented on src/test/java/potatoes/server/ServerApplicationTests.java
> +@EnableJpaAuditing
테스트할때 막히던 부분이 있어서 이것저것 붙이고 때다가... 남았습니다... 후딱 지우곘습니다.

2024-12-01 13:43 UTC, tjvm0877 approved these changes

2024-12-01 13:44 UTC, jickDo commented
고생하셨습니다... 이야기 나누면서 많이 배웠습니다...!

2024-12-01 13:45 UTC, merged