✨ feature: 여행 모임 생성 기능 추가
Team-Talking-Potatoes/WeGo_BE pull request #33
Opened 2024-12-06 13:44 UTC by tjvm0877

## PR 타입

- [x] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Performance Improvement
- [ ] Bugfix
- [ ] Test Code
- [ ] Code style update (formatting, local variables)
- [ ] Other... Please describe:

## 개요

- 여행 모임 생성 기능 추가

close #31

2024-12-07 10:33 UTC, jickDo requested changes

2024-12-07 10:33 UTC, jickDo commented on src/main/java/potatoes/server/controller/TravelController.java
> +@RequestMapping("/api/travel")
P3: 엔드포인트 시작점을 **'/api'** 로 붙인 이유를 알 수 있을까요?? 
이부분은 취향차이여서 컨벤션을 맞추어야 할것 같습니다. 제 의견은 **/api**를 안쓰는 엔드포인트가 많아질 떄 구분용으로 유용할것 같지만, 만약 api만 다루는 서버이고 관행적인 이유라면  조심스럽게 때는것이 어떤가 요청드리고 싶습니다!

2024-12-07 10:33 UTC, jickDo commented on src/main/java/potatoes/server/controller/TravelController.java
> +@RequestMapping("/api/travel")
P3: 명세서에 적힌 엔드포인트와 조금 다른것 같아서 확인가능할까요??

2024-12-07 10:33 UTC, jickDo commented on src/main/java/potatoes/server/controller/TravelController.java
> +	public void createTravel(
P1: 아무것도 반환하지 않아도 ResponseEntity<Void>형식의 사용으로 변경으로 요청하고 싶습니다. 이것관련 해서 이것저것 찾아보다가 아래 레퍼런스에서 컨트롤러 일관성 관해서 언급한 글을 가져왔습니다.

https://stevenschwenke.de/ReturningAnEmptyResponseEntityInSpringMVC

2024-12-07 10:33 UTC, jickDo commented on src/main/java/potatoes/server/controller/TravelController.java
> +		@Authorization @Parameter(hidden = true) Long id,
P1: id라는것이 테이블 마다 있다보니 id는 명확한 id를 말해주는게 좋다고 생각합니다!!
id -> userId

2024-12-07 10:33 UTC, jickDo commented on src/main/java/potatoes/server/entity/Travel.java
>  	@Column(name = "travel_location", nullable = false)
P5: 위쪽에 isDomestic부분이 변경점이 아니여서 여기다가 잡습니다 ㅎㅎ
혹시 isDomestic부분에 private 접근제어자가 없는 이유에 대해서 알고 싶습니다!!

2024-12-08 09:58 UTC, tjvm0877 commented on src/main/java/potatoes/server/controller/TravelController.java
> +@RequestMapping("/api/travel")
@jickDo BaseUrl을 보통 `/api/v1/...`을 습관적으로 했었어서 인지 못하고있었습니다. 수정하겠습니다.

2024-12-08 10:00 UTC, tjvm0877 commented on src/main/java/potatoes/server/controller/TravelController.java
> +	public void createTravel(
반영하도록 하겠습니다.

2024-12-08 10:02 UTC, tjvm0877 commented on src/main/java/potatoes/server/controller/TravelController.java
> +		@Authorization @Parameter(hidden = true) Long id,
@jickDo 서비스 계층으로 넘길때는 반영했는데 Controller에서는 확인 못했네요. 수정하겠습니다.

2024-12-08 10:03 UTC, tjvm0877 commented on src/main/java/potatoes/server/entity/Travel.java
>  	@Column(name = "travel_location", nullable = false)
@jickDo 딱히 이유는 없었던 것 같습니다. 접근제어자를 추가해야겠네요.

2024-12-08 11:56 UTC, jickDo approved these changes
고생하셨습니다!!!

2024-12-08 12:00 UTC, merged