✨ feature: 비밀번호 재설정 상황 이메일 인증 및 토큰 유효성 검사
Team-Talking-Potatoes/WeGo_BE pull request #41
Opened 2024-12-09 08:10 UTC by jickDo

## PR 타입

- [x] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Performance Improvement
- [ ] Bugfix
- [ ] Test Code
- [ ] Code style update (formatting, local variables)
- [ ] Other... Please describe:

## 개요

비밀번호 재설정 상황 이메일 인증 및 토큰 유효성 검사

## 작업 및 변경 사항

비밀번호 재설정 상황 이메일 인증 및 토큰 유효성 검사 구현하였습니다.

이메일 인증은 회의에서 이야기 했던 것처럼 두가지 상황에서 유저 존재여부 확인을 나눴고, 토큰 유효성 검사는 조작된 토큰인지만 검사하게 바꿧습니다.

### 테스트 결과

- 기능이 변경되는 속도를 보니 테스트를 만드는 것보다 이번주 내에 기능을 모두 만드는것이 중요하다고 판단해서 테스트 구현 이슈에 올려두고 mvp끝나는대로 하는 방향으로 잡고싶습니다.

### 공유 하고 싶은 내용 및 참고 자료

- 메일 서비스에 너무 많은 역할이 붙는것 같아, 기존 메일서비스를 메일 관련처리 기능만 하는 서비스로 변경하고 유저의 정보처리와 여러가지 기능을 퍼사드 느낌의 **MailVerificationService** 로 이전하였습니다.
- 퍼사드에 대한 고민을 많이 했는데, 퍼사드의 단점인 공통집합이 모이면서 방대해진다는 문제가 현재 메일 전송에 인증 정도만 하는 서비스 단에서는 방대해질 가능성이 낮다고 판단하여 퍼사드로 분리했습니다.
- 기존에 레디스 템플릿을 코드단에서 바로 사용했는데, 그것보다 레디스를 다루는 담당 구현체를 생성해서 핸들링 하는 방향이 유지보수와 가독성 측면에서 좋다고 생각해서 분리했습니다.
- 토큰 유효성 검사는 이메일 인증이 완료된 시점에 토큰을 던지는 것을 검사하면 되게 만들어 뒀고, 서버 시크릿키 이용해서 조작된 토큰인지만 검사하게 했습니다.

close #40

2024-12-09 09:33 UTC, tjvm0877 requested changes

2024-12-09 09:33 UTC, tjvm0877 commented on src/main/java/potatoes/server/dto/AccessToken.java
> +	String accessToken
P4: dto이름이 살짝 애매할 것 같습니다. 단일 `accessToken`만 반환한다면 굳이 dto로 감싸는게 맞을까라는 생각이 듭니다. 추가기능을 가정한다고하면 verifyResponse같은 역할이 명확하게 파악되는 이름이 더 좋지 않을까 생각합니다.

2024-12-09 09:33 UTC, tjvm0877 commented on src/main/java/potatoes/server/service/UserService.java
> +	}
P2: 이 코드는 이미 똑같은 조건을 `AuthorizationArgumentResolver`에서 검증하고 들어오지 않나요? `@Authorization`을 사용해도 되지않나 싶은데 이렇게 구현하신 이유가 있을까요?

2024-12-09 18:53 UTC, jickDo commented on src/main/java/potatoes/server/dto/AccessToken.java
> +	String accessToken
`'단일 accessToken만 반환한다면 굳이 dto로 감싸는게 맞을까라는 생각이 듭니다.'`-> 단일 값 반환에 Dto를 쓰는 이유는 두 가지 장점이 있다고 생각합니다. 첫번째는 추가 변경에 대응 가능하다, 두번째는 반환의 형태가 모든 api에서 동일한 Json형태로 반환 되어 api 일관성을 챙기고 프론트엔드가 데이터를 핸들링 하기 더 쉽게 하기 위함이였습니다.

이름은 accessToken 보다 다른 역할을 주는 이름이 더 적합한것 같습니다! 저는 verifyResponse이름 엄청 좋은거같아 이대로 가려고 합니다!

2024-12-09 19:09 UTC, jickDo commented on src/main/java/potatoes/server/service/UserService.java
> +	}
이부분은 토큰에 어떤 값을 담을까 하다가 따로 뺀 부분이었습니다. 기존 로직이 들어가는 값은 string인데 나올때는 Long타입으로 나오게 되어서 나올떄도 string으로 나오게 하려고 했는데,`LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss")))` 토큰 생성부에 이걸 담아주게 바꿧습니다.
기존 커스텀 어노테이션 사용하는쪽이 더 명확하고 재사용성이 높은거 같아 말씀대로 변경했습니다.
토큰에 유의미한 값을 담는것이 의미 있기보다 위조 판단이 주요목적이니 시간넣어주는게 딱인것 같아 그렇게 진행하겠습니다.

2024-12-11 04:58 UTC, tjvm0877 approved these changes

2024-12-11 04:58 UTC, tjvm0877 commented on src/main/java/potatoes/server/dto/ResetPasswordRequest.java
> +	String newPassword
P4: 똑같은 메시지를 쓰는 것 보다 "현재 비밀번호는 필수입니다."이렇게 어떤 파라미터가 잘못 혹은 누락됬는지 알려주는게 좋을 것 같다고 생각합니다.

2024-12-11 05:05 UTC, jickDo commented on src/main/java/potatoes/server/dto/ResetPasswordRequest.java
> +	String newPassword
생각도 못했는데 엄청 중요한 포인트네요 감사합니다 :)

2024-12-11 05:06 UTC, merged