✨ feat: 여행 생성 기능 API스펙 변경사항 적용
Team-Talking-Potatoes/WeGo_BE pull request #43
Opened 2024-12-12 11:24 UTC by tjvm0877

## PR 타입

- [x] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Performance Improvement
- [ ] Bugfix
- [ ] Test Code
- [ ] Code style update (formatting, local variables)
- [ ] Other... Please describe:

## 개요
API 스펙 변경에 따른 Entity, DTO, Service 코드 수정 

## 작업 및 변경 사항

- 여행 생성 데이터에 다음과 같은 데이터가 추가되었습니다.
   1.`startAt`, `endAt`에 시간(hh:MM)까지 포함
   2. 여행 모집 마감날짜(`registrationEnd`) 추가

close #42

2024-12-13 00:32 UTC, jickDo requested changes

2024-12-13 00:32 UTC, jickDo commented on src/main/java/potatoes/server/entity/Travel.java
> +	private Instant registrationEnd;
P5: 이건 제가 몰라서 질문드리는 건데, **registrationEnd** 이게 어떤곳에서 쓰이는 칼럼인가욥

2024-12-13 00:32 UTC, jickDo commented on src/main/java/potatoes/server/service/TravelService.java
>  			.isDomestic(request.getIsDomestic())
P1: 이전 pr에 대한 내용인데 이 부분은 제가 놓쳤었네요. **.image(travelImageUrl)** 위쪽에 이 부분이 의도사항이랑 조금 달라서 말씀드립니다! 변수명이 ~Url인것 보면 s3이미지 호스팅 주소를 말하는거 같은데, **uploadFile**이부분은 업로드를 수행하고 파일 이름을 리턴하는 메서드이며, **getFileUrl** 이 메서드가 파일주소를 리턴해줍니다.

2024-12-13 08:14 UTC, tjvm0877 commented on src/main/java/potatoes/server/service/TravelService.java
>  			.isDomestic(request.getIsDomestic())
@jickDo 확인 감사드립니다. 혹시 이부분 분리 이유가 뭔지 알 수 있을까요?

2024-12-13 11:18 UTC, jickDo commented on src/main/java/potatoes/server/service/TravelService.java
>  			.isDomestic(request.getIsDomestic())
책임 분리입니다. 파일생성 시점에 url을 리턴하면 파일이름이 필요한 경우가 생겨도 찾을 수 없고, **uploadFile**, **uploadFiles** 에 기능을 추가하면 결국 중복 코드가 생기며, 변경사항에 대해 유연하게 대응못한다고 생각합니다. utils클래스에서 많은것을 정해놓고 가는것보다 필요한게 있으면 비즈니스 로직에서 풀어서 사용하는것이 맞다는 생각입니다.
공통 클래스가 god object가 되는순간 그걸 사용하는 모든 로직의 변경에 영향이 올수있다는 점을 피하고 싶었습니다.

2024-12-14 06:57 UTC, jickDo approved these changes
고생하셨습니다!!

2024-12-17 09:36 UTC, merged